name: cffconvert

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  verify:
    name: "cffconvert"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out a copy of the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cffconvert
        run: pip install cffconvert

      - name: Validate CITATION.cff
        run: cffconvert --validate CITATION.cff
